### ISSUE TITLE
Build does not render dithering effects

### ISSUE THREAD

**Issue by Fqlox** [Ooseykins/QuickDither#1]
Hi,

First of all thanks for this great postprocessing effect ! 

Though I got some issues with it, it renders great in the in-game unity view but when build it does not appear.
I tried with both custom and Example palette. 

Here in the interface :

![dithering1](https://user-images.githubusercontent.com/33659731/197247663-aa84eaea-6523-4ec9-a26a-34b3d92a5c52.PNG)

And here once build : 
![dithering2](https://user-images.githubusercontent.com/33659731/197247673-a1e7c81d-76c9-4224-be53-526565300921.PNG)

Is there something to do with linking the palette with the build with streaming assets ?

Thanks in advance

**Comment by Ooseykins** [comment]
For some reason the shader doesn't automatically get included in builds. You can add it to the list manually (Project Settings -> Graphics -> Always Included Shaders)
