### ISSUE TITLE
1-bit results seem flipped

### ISSUE THREAD

**Issue by dan-hansen** [Ooseykins/QuickDither#3]
Thanks again for making this. I am having some trouble applying it to a 1-bit palette. The results seem to be the opposite of what I am expecting when it goes to fill the gradients with the bayer pattern. The darker patterns are where the color should be coming out lighter. I think what I am looking for is for white and black to be flipped in order. Any idea how the shader or input can be adjusted to get the right result? I really have no idea how this works.
![1-bit](https://github.com/Ooseykins/QuickDither/assets/77889523/d2c8e08a-df03-4f4f-904b-a412f54e1271)

**Comment by Ooseykins** [comment]
On the material is the primary texture set as primary and the secondary texture set as secondary? I think this mix up here could cause the flipping like this.

**Comment by dan-hansen** [comment]
Simple solution. I thought o tried that already. Seems to have same effect as flipping the inputs on the either of last nodes in shader as well. Makes sense.

**Comment by dan-hansen** [comment]
But to clarify I had to set primary to secondary and secondary to primary in the case of black and white.
